// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriFlow.Infrastructure.Persistence;

#nullable disable

namespace NutriFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NutriFlowDbContext))]
    [Migration("20261004192925_AddLabelPhotoOwnership")]
    partial class AddLabelPhotoOwnership
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.DailyGoalRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Calories")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarbohydratesGrams")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "Date");

                    b.ToTable("DailyGoals", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.LabelPhotoRecord", b =>
                {
                    b.Property<string>("FileName")
                        .HasMaxLength(37)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("FileName");

                    b.HasIndex("UserId");

                    b.ToTable("LabelPhotos", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.MealEntryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Calories")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarbohydratesGrams")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MealDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MealSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightInGrams")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MealDate");

                    b.HasIndex("MealSessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("MealEntries", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.MealSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MealDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageRequestHashesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalRequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("MealSessions", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.ProductAliasRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "NormalizedName");

                    b.HasIndex("UserId", "ProductId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("ProductAliases", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.ProductRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Calories")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarbohydratesGrams")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatGrams")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProteinGrams")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceQuality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NULL AND \"Barcode\" IS NOT NULL");

                    b.HasIndex("UserId", "Barcode")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL AND \"Barcode\" IS NOT NULL");

                    b.HasIndex("UserId", "NormalizedName");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLegacyLocal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LegacyLabelPhotosImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("IsLegacyLocal")
                        .IsUnique()
                        .HasFilter("\"IsLegacyLocal\" = 1");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.DailyGoalRecord", b =>
                {
                    b.HasOne("NutriFlow.Infrastructure.Persistence.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.LabelPhotoRecord", b =>
                {
                    b.HasOne("NutriFlow.Infrastructure.Persistence.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.MealEntryRecord", b =>
                {
                    b.HasOne("NutriFlow.Infrastructure.Persistence.MealSessionRecord", "MealSession")
                        .WithMany("MealEntries")
                        .HasForeignKey("MealSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealSession");
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.MealSessionRecord", b =>
                {
                    b.HasOne("NutriFlow.Infrastructure.Persistence.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.ProductAliasRecord", b =>
                {
                    b.HasOne("NutriFlow.Infrastructure.Persistence.ProductRecord", "Product")
                        .WithMany("Aliases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriFlow.Infrastructure.Persistence.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.ProductRecord", b =>
                {
                    b.HasOne("NutriFlow.Infrastructure.Persistence.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.MealSessionRecord", b =>
                {
                    b.Navigation("MealEntries");
                });

            modelBuilder.Entity("NutriFlow.Infrastructure.Persistence.ProductRecord", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
