<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == '' and $([MSBuild]::IsOSPlatform('osx'))">net10.0-ios</TargetFramework>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>NutriFlow.Mobile</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <MauiVersion>10.0.0</MauiVersion>
    <ApplicationTitle>NutriFlow</ApplicationTitle>
    <ApplicationId>com.nutriflow.app</ApplicationId>
    <ApplicationDisplayVersion>0.2.0</ApplicationDisplayVersion>
    <ApplicationVersion>2</ApplicationVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">android-arm;android-arm64;android-x64</RuntimeIdentifiers>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <NuGetLockFilePath>packages.$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')).lock.json</NuGetLockFilePath>
    <NuGetLockFilePath Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' and $([MSBuild]::IsOSPlatform('linux'))">packages.android-ci.lock.json</NuGetLockFilePath>
  </PropertyGroup>

  <ItemGroup>
    <MauiIcon Include="Resources/AppIcon/appicon.svg" Color="#185B45" />
    <MauiSplashScreen Include="Resources/Splash/splash.svg" Color="#185B45" BaseSize="128,128" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <ProjectReference Include="../NutriFlow.Mobile.Core/NutriFlow.Mobile.Core.csproj" GlobalPropertiesToRemove="TargetFramework;RuntimeIdentifier;RuntimeIdentifiers" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
    <BundleResource Include="Platforms/iOS/PrivacyInfo.xcprivacy" LogicalName="PrivacyInfo.xcprivacy" />
  </ItemGroup>

</Project>
